"""empty message

Revision ID: 0c88945b1e4c
Revises: e37fe3cb94a0
Create Date: 2020-12-17 13:16:32.361720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c88945b1e4c'
down_revision = 'e37fe3cb94a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('lga',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(length=150), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('lga',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
