"""empty message

Revision ID: d30290c9dde0
Revises: dd6dc3471237
Create Date: 2020-12-16 17:09:03.091992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30290c9dde0'
down_revision = 'dd6dc3471237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_login_at')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('login_count')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('current_login_ip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_login_ip', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('current_login_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
