"""empty message

Revision ID: e08de8933907
Revises: f2e9af794835
Create Date: 2021-01-04 09:34:03.669496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08de8933907'
down_revision = 'f2e9af794835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('constituency')
        batch_op.drop_column('district')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('constituency', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
